### ISSUE TITLE
snakepacker/python:3.9 image includes Python 3.8

### ISSUE THREAD

**Issue by j0nm1** [snakepacker/python#6]
Hi, 
I just discovered your really great python images. 

Nearly all of them are pretty usable for me but I'm a little bit confused why the `snakepacker/python:3.9` does include Python 3.8.10 besides Python 3.9.5. Is there any reason for this? Because this seems not right to me.

**Comment by mosquito** [comment]
This is not a bug, it is rather a feature of ubuntu and the `python3-distutils` package, as it requires the installation of `python3` package which in ubuntu:focal is 3.8
