### ISSUE TITLE
Fix for `ImportError: cannot import name 'html5lib' from 'pip._vendor'`

### ISSUE THREAD

**Issue by michael-k** [snakepacker/python#7]
This has been fixed in deadsnakes 2 days ago, see deadsnakes/issues#182.  The last update of https://hub.docker.com/r/snakepacker/python was 19 days ago.  Could you please rebuild and push?

**Comment by mosquito** [comment]
Yes, it's should be fixed here.

**Comment by mosquito** [comment]
I rebuild locally as a quick solution, but the automation needs to be fixed. Now you can already try to use the updated image.

**Comment by michael-k** [comment]
I seems this wasn't enough to fix the problem: https://github.com/mosquito/aiormq/runs/4584031147?check_suite_focus=true
The sha256 pulled by GitHub Actions matches the one listed on Docker Hub.

**Comment by mosquito** [comment]
Fixed
