### ISSUE TITLE
Add multi-arch builds

### ISSUE THREAD

**Issue by ddelange** [snakepacker/python#8]
Hi 👋 

We would love to use your setup to run on aarch64 machines (arm64/v8), now that more and more projects (e.g. numpy, pandas) have started publishing `macosx_11_0_arm64` and `manylinux2014_aarch64` wheels.

Example of official Python image architectures:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/14880945/157847487-bf07b22b-b001-4cf2-a253-d0dc75709b42.png">

Adding multi-arch support using QEMU should be more or less straight forward, e.g. https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

**Comment by mosquito** [comment]
This repository provides python with ubuntu, so now the armv7 and arm64 was added. Of course windows version was not will be added.

**Comment by ddelange** [comment]
Awesome stuff, thanks a lot! Very happy with this setup, will try out multi-arch soon!
